services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-bank
    environment:
      MYSQL_ROOT_PASSWORD: greekgod
      MYSQL_DATABASE: bankappdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bank-network

  bankapp:
    build: .
    container_name: bankapp-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/bankappdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: greekgod
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    networks:
      - bank-network

  
  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent-bankapp
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_HOSTNAME: bankapp-server
      ZBX_METADATA: bankapp
    ports:
      - "10050:10050"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./zabbix-agent:/etc/zabbix/zabbix_agentd.d:ro
    networks:
      - bank-network
      - zabbix-net
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  bank-network:
    driver: bridge
  zabbix-net:
    external: true
    name: 3-tier-banking-app_zabbix-net